type Videogame {
    id: ID!
    title: String
    genre: String
    releaseYear: Int
    studio: String
    price: Float
    description: String
    ageRating: String
    status: String
}

input VideogameDto {
    title: String
    genre: String
    releaseYear: Int
    studio: String
    price: Float
    description: String
    ageRating: String
    status: String
}

type Query {
    getAllVideogames: [Videogame]
    getRecentVideogames(count: Int, offset: Int): [Videogame]
    getVideogameById(id: ID!): Videogame
    getVideogamesByGenre(genre: String!): [Videogame]
}

type Mutation {
    deleteVideogameById(id: ID!): Videogame
    saveVideogame(videogameDto: VideogameDto!): Videogame
}